/* Generated By:JJTree: Do not edit this line. .\compilerTreeConstants.java */

package com.CmmCompiler.interpreter;

public interface compilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMT = 1;
  public int JJTBREAKSTMT = 2;
  public int JJTSTMTBLOCK = 3;
  public int JJTVARDECL = 4;
  public int JJTTYPE = 5;
  public int JJTVARLIST = 6;
  public int JJTIFSTMT = 7;
  public int JJTSWITCHSTMT = 8;
  public int JJTCRITERION = 9;
  public int JJTWHILESTMT = 10;
  public int JJTREADSTMT = 11;
  public int JJTWRITESTMT = 12;
  public int JJTASSIGNSTMT = 13;
  public int JJTVALUE = 14;
  public int JJTEXPRESSION = 15;
  public int JJTTERM = 16;
  public int JJTELEMENT = 17;


  public String[] jjtNodeName = {
    "Start",
    "Stmt",
    "BreakStmt",
    "StmtBlock",
    "varDecl",
    "Type",
    "VarList",
    "IfStmt",
    "SwitchStmt",
    "Criterion",
    "WhileStmt",
    "ReadStmt",
    "WriteStmt",
    "AssignStmt",
    "Value",
    "Expression",
    "Term",
    "Element",
  };
}
