/* Generated By:JJTree&JavaCC: Do not edit this line. compilerConstants.java */
package com.CmmCompiler.interpreter;

public interface compilerConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int KWIF = 9;
  int KWELSE = 10;
  int KWWHILE = 11;
  int KWBREAK = 12;
  int KWREAD = 13;
  int KWWRITE = 14;
  int KWINT = 15;
  int KWDOUBLE = 16;
  int KWBOOLEAN = 17;
  int KWSWITCH = 18;
  int KWCASE = 19;
  int KWDEFAULT = 20;
  int PLUS = 21;
  int MINUS = 22;
  int MULTIPLY = 23;
  int DIVIDE = 24;
  int MOD = 25;
  int LESS_THAN = 26;
  int GREATER_THAN = 27;
  int LESS_EQUAL = 28;
  int GREATER_EQUAL = 29;
  int EQUAL = 30;
  int NOT_EQUAL = 31;
  int ASSIGNMENT = 32;
  int LPARENTHESIS = 33;
  int RPARENTHESIS = 34;
  int LBRACKET = 35;
  int RBRACKET = 36;
  int LBLOCK = 37;
  int RBLOCK = 38;
  int COMMA = 39;
  int COLON = 40;
  int EOL = 41;
  int INTEGER_CONSTANT = 42;
  int DOUBLE_CONSTANT = 43;
  int BOOLEAN_CONSTANT = 44;
  int DIGIT = 45;
  int IDENTIFIER = 46;
  int LETTER = 47;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"break\"",
    "\"read\"",
    "\"write\"",
    "\"int\"",
    "<KWDOUBLE>",
    "\"bool\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "<NOT_EQUAL>",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "<INTEGER_CONSTANT>",
    "<DOUBLE_CONSTANT>",
    "<BOOLEAN_CONSTANT>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
