/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.CmmCompiler.interpreter;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

public @SuppressWarnings("all")
class SimpleNode implements Node {

	protected Node parent;
	protected Node[] children;
	protected int id;
	protected ArrayList value;
	//protected Object value;
	protected compiler parser;
	String result="";

	public SimpleNode(int i) {
		id = i;
		value = new ArrayList();
	}

	public SimpleNode(compiler p, int i) {
		this(i);
		parser = p;
		value = new ArrayList();
	}

	public void jjtOpen() {
	}

	public void jjtClose() {
	}

	public void jjtSetParent(Node n) {
		parent = n;
	}

	public Node jjtGetParent() {
		return parent;
	}

	public void jjtAddChild(Node n, int i) {
		if (children == null) {
			children = new Node[i + 1];
		} else if (i >= children.length) {
			Node c[] = new Node[i + 1];
			System.arraycopy(children, 0, c, 0, children.length);
			children = c;
		}
		children[i] = n;
	}

	public Node jjtGetChild(int i) {
		return children[i];
	}

	public int jjtGetNumChildren() {
		return (children == null) ? 0 : children.length;
	}

	public void jjtSetValue(Object value) {
		this.value.add(value);
	}

	public Object jjtGetValue(int i) {
		return this.value.get(i);
	}
	
	public int jjtValueLength() {
		return this.value.size();
	}

	/*
	 * You can override these two methods in subclasses of SimpleNode to
	 * customize the way the node appears when the tree is dumped. If your
	 * output uses more than one line you should override toString(String),
	 * otherwise overriding toString() is probably all you need to do.
	 */

	public String toString() {
		return compilerTreeConstants.jjtNodeName[id];
	}

	public String toString(String prefix) {
		return prefix + toString();
	}

	/*
	 * Override this method if you want to customize how the node dumps out its
	 * children.
	 */

	public String dump(String prefix) throws IOException {		
		result += toString(prefix) + "\n";
		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					result += n.dump(prefix+"    ");
				}
			}
		}
		return result;
	}
}

/*
 * JavaCC - OriginalChecksum=501f610f91ff7c10496d33bec2aa08b4 (do not edit this
 * line)
 */
